server:
  port: 8080
  servlet:
    context-path: /

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: playkuround@gmail.com
    password: xbccdckhfdcadtba
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          starttls:
            required: true
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true

    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace

token:
  secret: ENC(P7i3h2tf8pxFcVRjXhOQYT//HTk/u7MgwKpcPHkd6+A=)
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1.577e+10 # 6개월

management:
  endpoint:
    health:
      show-details: always


