server:
  port: 8080
  servlet:
    context-path: /

spring:
  mail:
    host:
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          port: 465
          auth: true
          starttls:
            required: true
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace

token:
  secret: testjwtsecret124testjwtsecret124testjwtsecret124testjwtsecret
  issuer: playkuround
  access-token-expiration-seconds: 7200 # 2시간
  refresh-token-expiration-seconds: 1209600 # 2주
  authverify-token-expiration-seconds: 300 # 5분

authentication:
  email:
    domain:
    max-send-count:
    code-length:
