-- Test 실행 시 필요한 랜드마크 초기 데이터입니다. h2 문법에 맞춰져 있습니다.
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.539927, 127.073006, '산학협동관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.540158, 127.073463, '입학정보관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.539314, 127.074319, '수의학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.540099, 127.073976, '동물생명과학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541211, 127.073883, '생명과학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541648, 127.073841, '상허도서관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541638, 127.072255, '의생명과학연구관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542775, 127.073131, '예디대', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542419, 127.074791, '언어교육원', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541611, 127.075364, '법학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542386, 127.075947, '상허박물관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543215, 127.075319, '행정관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543853, 127.074704, '교육과학관(사범대)', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.534982, 127.075425, '상허연구관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.544106, 127.076126, '경영관', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543502, 127.076867, '새천년관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543799, 127.078138, '건축관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543468, 127.078121, '부동산학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542445, 127.077996, '인문학관(인문대)', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542203, 127.077553, '학생회관', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541457, 127.078315, '제2학생회관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541755, 127.078681, '공학관 A', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (23, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542101, 127.079445, '공학관 B', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (24, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541135, 127.079324, '공학관 C', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.540884, 127.079518, '신공학관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541250, 127.080375, '과학관(이과대)', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (27, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.540829, 127.081378, '창의관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (28, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542095, 127.080905, '공예관', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (29, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0.000000, 0.000000, '국제학사', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (30, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.539212, 127.077411, '기숙사', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (31, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0.000000, 0.000000, '일감호', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (32, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541811, 127.077443, '홍예교', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (33, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.543101, 127.076137, '황소동상', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (34, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.542416, 127.076804, '청심대', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (35, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541373, 127.073451, '상허박사 동상', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (36, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541475, 127.077802, '노천극장 중앙', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (37, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.544147, 127.076972, '운동장', 'QUIZ');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (38, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.544523, 127.079606, '실내체육관', 'TIMER');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (39, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.544838, 127.076628, '건국문(후문)', 'MOON');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (40, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0.000000, 0.000000, '중문', 'MOON');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (41, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0.000000, 0.000000, '일감문(동물병원)', 'MOON');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (42, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0.000000, 0.000000, '상허문(도서관)', 'MOON');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (43, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.541454, 127.082172, '구의역쪽문', 'MOON');
insert into "landmark" ("id", "created_at", "updated_at", "latitude", "longitude", "name", "game_type") values (44, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 37.539222, 127.076744, '기숙사쪽문', 'MOON');