name: Java CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options:
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
  
      - name: Copy secret
        env:
          SECRET_YML: ${{ secrets.YML }}
          SECRET_TEST_YML: ${{ secrets.TEST_YML }}
        run: |
          echo "$SECRET_YML" > src/main/resources/application.yml
          echo "$SECRET_TEST_YML" > src/main/resources/application-test.yml
        shell: bash
  
      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6
  
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        
      - name: Build with Gradle
        run: ./gradlew clean build
